# Generated by Django 3.0rc1 on 2019-11-28 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalUnifap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('descricao', models.CharField(max_length=140)),
                ('status', models.SmallIntegerField(choices=[(0, 'Não Resolvido'), (1, 'Resolvido'), (2, 'Não será resolvido')], default=0)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visible', models.SmallIntegerField(choices=[(1, 'Está Visível'), (0, 'Não está visível')], default=1)),
                ('image', models.FileField(upload_to='')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alert.LocalUnifap')),
            ],
        ),
    ]
