# Generated by Django 2.2.7 on 2019-11-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localunifap',
            name='nome',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='nome',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
