# Generated by Django 2.2.7 on 2019-11-30 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_auto_20191128_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='visible',
        ),
    ]
