# Generated by Django 2.2.7 on 2019-11-09 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_auto_20191108_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='latitute',
            new_name='latitude',
        ),
    ]
