# Generated by Django 3.0b1 on 2019-11-19 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_auto_20191118_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='visible',
            field=models.SmallIntegerField(choices=[(1, 'Está Visível'), (0, 'Não está visível')], default=1),
        ),
    ]
