# Generated by Django 2.2.7 on 2019-12-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0003_remove_alert_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='feedback',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
